### ISSUE TITLE
[Alpha Update] Support for Wallet Events!

### ISSUE THREAD

**Issue by toooo** [IOTA-NET/IotaSDK.NET#274]
Hi!

Here I have stumbled on [event](https://www.tangleverse.io/events) but can not find more info and source of this information
Can you help with example code and best approach to build payment gateway for shimmer native tokens? 
https://discord.com/channels/397872799483428865/399178054909296640/1201844805093818369

Thank you!

**Comment by wireless90** [comment]
hi we have put up examples on wallet events subscriptions.

https://github.com/IOTA-NET/IotaSDK.NET/blob/main/IotaSDK.NET.Main/Examples/Events/Subscribe%20To%20Events/README.md

For your question regarding building a payment gateway, better to discuss it in discord with others.
